### ISSUE TITLE
Make it more obvious what this does!

### ISSUE THREAD

**Issue by ColinEberhardt** [AntoineViau/tweetx86#1]
This is an awesome project ... but ... it took me a little while to understand what it does. The webpage itself doesn't really provide much of a description. The GitHub README is a little better:

> Enter your x86 assembly code in the text box on the left, assemble and run.
When you assemble, the generated binary (a .COM file) is converted to base64 in the text box on the right.

Can I suggest that you simplify the UI? I don't think there is any need to show the base64 encoded version in it's own text field. I'd just display the shareable twitter link.

Also, is there any need to display the length of the URL? Twitter will use it's own shortener, so you can actually tweet very long URLs :-)

**Comment by AntoineViau** [comment]
Thanks for the feedback, I really appreciate it.
I wanted to keep the base64 to allow the user to show off the code in a tweet, the same way alokmenghrajani did : 

perl -E 'say"A"x46422,"BDRDAwMQFFTCBUT1JJVE8gU1BFQ0lGSUNBVElPTg","A"x54,"Ew","A"x2634,"/0NEMDAxAQ","A"x2721,"BAAAAYQ","A"x30,"SVVVqogAAAAAAAEAF","A"x2676,"LMBaACgB76gfbgTAM0Qv8D4uYAI86qqgcc+AXP45GA8SHIRPFB3DTeYSEhyBSwCa8CwicMB3rSGtkDNFSYwJHvc68MA","VapVqlWq"x330'|base64 -D>cd.iso

But I think you are right. It is a bit too much for a newcomer, especially from the front-end world, to understand the project purpose. I simplified the UI, it's available on http://twt86.co

What do you think of theses changes ?
