### ISSUE TITLE
NASM crashes chrome with "Aw Snap"!

### ISSUE THREAD

**Issue by warpcoil** [AntoineViau/tweetx86#2]
I think we're both having the same problem with NASM.  Your version of NASM crashed chrome as did my version.

For example: when assembling snake.asm at the assembling stage we are greeted with:

![image](https://user-images.githubusercontent.com/5113027/57201081-bfc4e500-6f8b-11e9-8d23-00cc57058c50.png)

**Comment by warpcoil** [comment]
Ok testing with non Chrome Microsoft Edge, it runs very fine.
Testing with Firefox, it runs fine.

Any clues?

**Comment by AntoineViau** [comment]
Well, I work on Linux Mint and it works well on my Chrome...
Can't help you on this one.
